version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: n8n_postgres
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:1.112.4
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: "America/Sao_Paulo"
      TZ: "America/Sao_Paulo"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
      N8N_CUSTOM_EXTENSIONS: /home/node/custom-nodes
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
      - ./custom-nodes:/home/node/custom-nodes

volumes:
  n8n_data:
  postgres_data:
